# Generated by Django 4.0.6 on 2022-07-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_photo_image_alter_image_sighting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='sighting',
            new_name='finch',
        ),
    ]
